### ISSUE TITLE
Apply prefix text as suffix text

### ISSUE THREAD

**Issue by mebonilla9** [eralpyucel/CircleProgressView#1]
Apply prefix text as suffix text.

More than a problem is a query, is there any way to make the % symbol be a suffix of the text of the view or would it be necessary to recompile the library?

**Comment by eralpyucel** [comment]
@mebonilla9 

Update your dependencies to:
`compile 'com.github.eralpyucel:CircleProgressView:v1.1'`

And you can use:
`app:cpv_text_prefix="%"`
`app:cpv_text_suffix="%"`

or both of them.

**Comment by mebonilla9** [comment]
Thank you very much, it is a great help to have your prompt solution, I am very grateful
