### ISSUE TITLE
Text hidden

### ISSUE THREAD

**Issue by princeHago** [eralpyucel/CircleProgressView#7]
Hi,

i use your component but i don't see the text into circle progress view.

This is the xml
```
<com.eralp.circleprogressview.CircleProgressView
            android:id="@+id/circle_progress_view"
            android:layout_width="0dp"
            android:layout_weight=".2"
            android:layout_height="50sp"
            android:layout_gravity="center"
            android:layout_margin="3sp"
            app:cpv_circle_color="@color/White"
            app:cpv_circle_width="2dp"
            app:cpv_background_circle_width="1dp"
            app:cpv_background_circle_color="#5b253048"
            app:cpv_text_suffix="xp"
            app:cpv_text_size="15"
            app:cpv_text_color="@color/White"/>
```
This is the code
```
holder.mCircleProgressView.setTextEnabled(true);
        holder.mCircleProgressView.setInterpolator(new AccelerateDecelerateInterpolator());
        holder.mCircleProgressView.setStartAngle(45);
        holder.mCircleProgressView.setProgressWithAnimation(Float.parseFloat(((ProfiloBEAN) lst.get(position)).getPercentuale()), 3000);
        holder.mCircleProgressView.addAnimationListener(new ProgressAnimationListener() {
            @Override
            public void onValueChanged(float value) {
            }

            @Override
            public void onAnimationEnd() {
            }
        });
```
Can you help me?

Thanks in advance

**Comment by eralpyucel** [comment]
Hi,
What is your circle_progress_view 's parent view background colour? Because your cpv_text_color is white. @princeHago

**Comment by princeHago** [comment]
Hi,

i know, indeed the back color is blue.

I use your component in a layout for each row of a listview.

This is the parent of circle:
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/border_radius"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:custom="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical" >
```

This is the code of border_radius:
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- Bottom 2dp Shadow -->
    <item>
        <shape  android:shape="rectangle">
            <solid android:color="#33d8d8d8" />
            <corners android:radius="3dp" />
        </shape>
    </item>
    <!-- White Top color -->
    <item android:bottom="3px">
        <shape  android:shape="rectangle">
            <solid android:color="@color/BlueIcon" />
            <corners android:radius="3dp" />
        </shape>
    </item>
</layer-list>
```
And this is the code of BluIcon
`<color name="BlueIcon">#08a5c0</color>`

The strange thing is that for a while it worked, then no more.

Can it be in conflict with some other addiction?

**Comment by eralpyucel** [comment]
Ok. This is just a sample.

Layout:
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="todo.eralpyucel.com.myapplication.MainActivity"
    android:padding="10dp">

    <ListView
        android:id="@+id/listView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</LinearLayout>

row:

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/border_radius"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

    <com.eralp.circleprogressview.CircleProgressView
        android:id="@+id/circle_progress_view"
        android:layout_width="100dp"
        android:layout_height="50sp"
        android:layout_gravity="center"
        android:layout_margin="3sp"
        app:cpv_circle_color="@android:color/white"
        app:cpv_circle_width="2dp"
        app:cpv_background_circle_width="1dp"
        app:cpv_background_circle_color="#5b253048"
        app:cpv_text_suffix="xp"
        app:cpv_text_size="15"
        app:cpv_text_color="@android:color/white" />

</LinearLayout>

Adapter:

```
public class MyListAdapter extends ArrayAdapter<Float> {
    private Float[] data;
    private int resource;
    private LayoutInflater mInflater;


    public MyListAdapter(Context context, int resource, Float[] data) {
        super(context, resource);
        this.data = data;
        this.resource = resource;
        this.mInflater = (LayoutInflater) context
                .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    }

    @Override
    public int getCount() {
        return data.length;
    }

    @NonNull
    @Override
    public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent) {

        ViewHolder holder;

        if (convertView == null) {
            convertView = mInflater.inflate(resource, parent, false);
            holder = new ViewHolder();
            holder.circleProgressView = (CircleProgressView) convertView.findViewById(R.id.circle_progress_view);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }

        holder.circleProgressView.setTextEnabled(true);
        holder.circleProgressView.setInterpolator(new AccelerateDecelerateInterpolator());
        holder.circleProgressView.setStartAngle(45);
        holder.circleProgressView.setProgressWithAnimation(data[position], 1400);
        holder.circleProgressView.addAnimationListener(new ProgressAnimationListener() {
            @Override
            public void onValueChanged(float value) {
            }

            @Override
            public void onAnimationEnd() {
            }
        });

        return convertView;
    }

    private static class ViewHolder {
        CircleProgressView circleProgressView;
    }
}
```

Activity onCreate:

```
listView = (ListView) this.findViewById(R.id.listView);

        Float[] values =
                {32f, 45f, 23f, 21f, 43f, 64f, 78f};

        MyListAdapter myListAdapter = new MyListAdapter(this, R.layout.item_list, values);

        listView.setAdapter(myListAdapter);
```

and the result looks like this:
![screenshot_20171010-195931](https://user-images.githubusercontent.com/11141271/31400021-db310cb8-adf6-11e7-918b-81f280b12e07.png)


It looks like no problem. I think you should check the values come from 
"(ProfiloBEAN) lst.get(position)).getPercentuale()"

or it's right,

try with not using "layout_weight"  it causes something on your layout maybe.
